[package]
name = "example-erc20-gas"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
revm = { workspace = true, features = ["std", "alloydb"] }

# tokio
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

# alloy
alloy-sol-types = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, default-features = true }
anyhow.workspace = true
