[package]
name = "example-cframe"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
revm = { path = "../../crates/revm", features = ["std", "serde"] }
hex = "0.4"

[[bin]]
name = "example-cframe"
path = "src/main.rs"