[package]
name = "revm-common-test-util"
version = "0.1.0"
authors = ["revm"]
edition = "2021"
rust-version = "1.80.1"
license = "MIT"
description = "Common test utilities for REVM crates"
repository = "https://github.com/bluealloy/revm"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]